[package]
name = "mini-agent-app-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A service boundary and JSON-RPC transport for mini-agent Threads"
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
mini-agent-capabilities = { version = "0.6.0", path = "../mini-agent-capabilities" }
mini-agent-core = { version = "0.6.0", path = "../mini-agent-core" }
mini-agent-app-server-protocol = { version = "0.6.0", path = "../mini-agent-app-server-protocol" }
mini-agent-host = { version = "0.6.0", path = "../mini-agent-host" }
mini-agent-protocol = { version = "0.6.0", path = "../mini-agent-protocol" }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-std", "io-util", "rt-multi-thread"] }

[dev-dependencies]
serde_json.workspace = true
